<?php require 'views/head.php'; ?>
<main class="container">
  <div class="row">
  	<table id="tblDetalle" class="hover compact cell-border" cellspacing="0" width="100%" style="font-size:70%;">
  		<thead>
  			<tr>
				<th>Id</th>
				<th>#</th>				
				<th>Usuario</th>
				<th>Correo</th>
				<th>Departamento</th>
				<th>Puesto</th>
				<th>Equipo</th>
				<th>CPU</th>
				<th>Serie</th>
				<th>Monitor</th>
				<th>Serie</th>
				<th>Teclado</th>
				<th>Serie</th>
				<th>Ratón</th>
				<th>Serie</th>
				<th>Bocinas</th>
				<th>Serie</th>
				<th>Lecto</th>
				<th>Serie</th>
				<th>Impresion</th>
				<th>IP</th>
				<th>Impresion</th>
				<th>IP</th>
				<th>Ethernet</th>
				<th>DireccionIP</th>
				<th>Wifi</th>
				<th>DireccionIP</th>
				<th>SistemaOperativo</th>
				<th>Licencia</th>
				<th>Observaciones</th>
				<th>Internet</th>
				<th>VersionOffice</th>
				<th>Licencia</th>
				<th>Observaciones</th>
				<th>Word</th>
				<th>Excel</th>
				<th>PowerPoint</th>
				<th>Outlook</th>
				<th>Visio</th>
				<th>Proyect</th>
				<th>CliCorreo</th>
				<th>FirmaCorreo</th>
				<th>Intelisis</th>
				<th>Apontar</th>
				<th>Jobtrack</th>
				<th>JTMonitor</th>
				<th>Planner</th>
				<th>Printware</th>
				<th>Crece</th>
				<th>Chrome</th>
				<th>Explorer</th>
				<th>Firefox</th>
				<th>Safari</th>
				<th>DBEMetrics</th>
				<th>DBEIntelisis</th>
				<th>Acr.Reader</th>
				<th>Acr.PRO</th>
				<th>Photoshop</th>
				<th>Ilustrator</th>
				<th>InDisign</th>
				<th>Dreamwever</th>
				<th>Starbucks</th>
				<th>KrispyKreme</th>
				<th>DBxtra</th>
				<th>SAAM</th>
				<th>DOTS</th>
				<th>MesaControl</th>
				<th>iDashboards</th>
				<th>Contizador</th>
				<th>Otro</th>
				<th>Requiere</th>
				<th>Otro</th>
				<th>Requiere</th>
				<th>PDFEditor</th>
				<th>iTunes</th>
				<th>Kies</th>
				<th>Lab.Matrix</th>
				<th>Antivirus</th>
				<th>Descripcion</th>
				<th>Escaner</th>
				<th>Descripcion</th>
				<th>Otro</th>
				<th>Requiere</th>
				<th>Otro</th>
				<th>Requiere</th>
				<th>Otro</th>
				<th>Requiere</th>
				<th>Unidad</th>
				<th>Ruta</th>
				<th>Unidad</th>
				<th>Ruta</th>  
				<th>Unidad</th>
				<th>Ruta</th>
				<th>Unidad</th>
				<th>Ruta</th>
				<th>Unidad</th>
				<th>Ruta</th>
				<th>Unidad</th>
				<th>Ruta</th>
				<th>NSTelefono</th>  
				<th>Extensión</th>
  			</tr>
  		</thead>
  		<tbody>
  			<!--Registros de la BDD-->
  		</tbody>
  	</table>
  </div>
</main>
<?php require '../layout/scripts.php'; ?>
<script type="text/javascript" src="js/detalleInventario.js"></script>

</body>
</html>